### ISSUE TITLE
Strange relative links 

### ISSUE THREAD

**Issue by 4integration** [AOEpeople/aoe_technology_radar#270] opened 2022-11-29 14:39 UTC
Hi,

We experience strange behavior  with relative links.

E.g. we have this page (rendered fine)
http://localhost:8090/languages-and-frameworks/dotnet.html

On that page we have a relative link as:

`[MS BizTalk](/platforms-and-services/ms-biztalk.html)`
but when that is rendered we get:

http://localhost:8090/languages-and-frameworks/undefined/platforms-and-services/ms-biztalk.html
i.e. **languages-and-frameworks/undefined** should not be present.

Do you have any idea what could be wrong?

**Comment by bastianccm** [comment] 2022-11-29 15:41
Hi @4integration,

that is new, but definitely wrong. I’ll have a look later this week, as this is for sure not the intended behavior.

**Comment by bastianccm** [comment] 2022-12-16 12:41
Hi @4integration,

the issue is resolved in #272 and released in version aoe_technology_radar@3.4.2.
I'll close this, feel free to re-open if this issue persists with version 3.4.2.

**Closed by bastianccm** 2022-12-16 12:41 UTC
Labels: bug
